<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

 class WP_Smartbanner_Options extends WP_Smartbanner {
	private $smartbanner_options;

	public function __construct() {
        $this->smartbanner_options = get_option( 'wp_smartbanner_options_fields' );
		add_action( 'admin_menu', [$this, 'smartbanner_add_plugin_page'] );
		add_action( 'admin_init', [$this, 'smartbanner_page_init'] );
	}

	public function smartbanner_add_plugin_page() {
		add_menu_page(
			_x('Smartbanner', 'backend', 'wp-smartbanner'), // page_title
			_x('Smartbanner', 'backend', 'wp-smartbanner'), // menu_title
			'manage_options', // capability
			'smartbanner', // menu_slug
			array( $this, 'smartbanner_create_admin_page' ), // function
			'dashicons-smartphone', // icon_url
			100 // position
		);
	}

	public function smartbanner_create_admin_page() { ?>
		<div class="wrap">
			<h2><?php echo _x('Smartbanner', 'backend', 'wp-smartbanner'); ?></h2>
			<p><?php echo _x('Customize the smartbanner settings.', 'backend', 'wp-smartbanner'); ?></p>
			<?php settings_errors(); ?>
			<form method="post" action="options.php">
				<?php
					settings_fields( 'smartbanner_option_group' );
					do_settings_sections( 'smartbanner-admin' );
					submit_button( _x('Save', 'backend', 'wp-smartbanner') );
				?>
			</form>
		</div>
	<?php }

	public function smartbanner_page_init() {

		register_setting(
			'smartbanner_option_group', // option_group
			'wp_smartbanner_options_fields', // option_name
			array( $this, 'smartbanner_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'smartbanner_setting_section', // id
			_x('Settings', 'backend', 'wp-smartbanner'),// title
			array( $this, 'smartbanner_section_info' ), // callback
			'smartbanner-admin' // page
		);

		add_settings_field(
			'app_name', // id
			_x('App name', 'backend', 'wp-smartbanner'), // title
			array( $this, 'app_name_callback' ), // callback
			'smartbanner-admin', // page
			'smartbanner_setting_section' // section
		);

		add_settings_field(
			'author_name', // id
			_x('Author name', 'backend', 'wp-smartbanner'), // title
			array( $this, 'author_name_callback' ), // callback
			'smartbanner-admin', // page
			'smartbanner_setting_section' // section
		);

		add_settings_field(
			'price', // id
			_x('Price label', 'backend', 'wp-smartbanner'), // title
			array( $this, 'price_callback' ), // callback
			'smartbanner-admin', // page
			'smartbanner_setting_section' // section
		);

		add_settings_field(
			'view_label', // id
			_x('View label', 'backend', 'wp-smartbanner'), // title
			array( $this, 'view_label_callback' ), // callback
			'smartbanner-admin', // page
			'smartbanner_setting_section' // section
		);

		add_settings_field(
			'close_label', // id
			_x('Close label', 'backend', 'wp-smartbanner'), // title
			array( $this, 'close_label_callback' ), // callback
			'smartbanner-admin', // page
			'smartbanner_setting_section' // section
		);

		add_settings_field(
			'show_on_ios', // id
			_x('Show on iOs', 'backend', 'wp-smartbanner'), // title
			array( $this, 'show_on_ios_callback' ), // callback
			'smartbanner-admin', // page
			'smartbanner_setting_section' // section
        );
    
        add_settings_field(
            'apple_app_store_url', // id
            sprintf('%s *', _x('Apple App Store url', 'backend', 'wp-smartbanner') ), // title
            array( $this, 'apple_app_store_url_callback' ), // callback
            'smartbanner-admin', // page
            'smartbanner_setting_section' // section
        );

        add_settings_field(
            'apple_app_store_icon_url', // id
            sprintf('%s *', _x('Apple App Store Icon url', 'backend', 'wp-smartbanner') ), // title
            array( $this, 'apple_app_store_icon_url_callback' ), // callback
            'smartbanner-admin', // page
            'smartbanner_setting_section' // section
        );

        add_settings_field(
            'apple_app_store_tagline', // id
            _x('Apple App Store tagline', 'backend', 'wp-smartbanner'), // title
            array( $this, 'apple_app_store_tagline_callback' ), // callback
            'smartbanner-admin', // page
            'smartbanner_setting_section' // section
        );

		add_settings_field(
			'show_on_android', // id
			_x('Show on Android', 'backend', 'wp-smartbanner'), // title
			array( $this, 'show_on_android_callback' ), // callback
			'smartbanner-admin', // page
			'smartbanner_setting_section' // section
        );
        
        add_settings_field(
            'google_play_store_url', // id
            sprintf('%s *', _x('Google Play Store url', 'backend', 'wp-smartbanner') ), // title
            array( $this, 'google_play_store_url_callback' ), // callback
            'smartbanner-admin', // page
            'smartbanner_setting_section' // section
        );

        add_settings_field(
            'google_play_store_icon_url', // id
            sprintf('%s *', _x('Google Play Store Icon url', 'backend', 'wp-smartbanner') ), // title
            array( $this, 'google_play_store_icon_url_callback' ), // callback
            'smartbanner-admin', // page
            'smartbanner_setting_section' // section
        );

        add_settings_field(
            'google_play_store_tagline', // id
            _x('Google Play Store tagline', 'backend', 'wp-smartbanner'), // title
            array( $this, 'google_play_store_tagline_callback' ), // callback
            'smartbanner-admin', // page
            'smartbanner_setting_section' // section
        );
        
	}

	public function smartbanner_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['app_name'] ) ) {
			$sanitary_values['app_name'] = sanitize_text_field( $input['app_name'] );
		}

		if ( isset( $input['author_name'] ) ) {
			$sanitary_values['author_name'] = sanitize_text_field( $input['author_name'] );
		}

		if ( isset( $input['price'] ) ) {
			$sanitary_values['price'] = sanitize_text_field( $input['price'] );
		}

		if ( isset( $input['view_label'] ) ) {
			$sanitary_values['view_label'] = sanitize_text_field( $input['view_label'] );
		}

		if ( isset( $input['close_label'] ) ) {
			$sanitary_values['close_label'] = sanitize_text_field( $input['close_label'] );
		}

		if ( isset( $input['show_on_ios'] ) ) {
			$sanitary_values['show_on_ios'] = $input['show_on_ios'];
		}

		if ( isset( $input['apple_app_store_url'] ) ) {
			$sanitary_values['apple_app_store_url'] = sanitize_text_field( $input['apple_app_store_url'] );
		}

		if ( isset( $input['apple_app_store_icon_url'] ) ) {
			$sanitary_values['apple_app_store_icon_url'] = sanitize_text_field( $input['apple_app_store_icon_url'] );
		}

		if ( isset( $input['apple_app_store_tagline'] ) ) {
			$sanitary_values['apple_app_store_tagline'] = sanitize_text_field( $input['apple_app_store_tagline'] );
		}

		if ( isset( $input['show_on_android'] ) ) {
			$sanitary_values['show_on_android'] = $input['show_on_android'];
		}

		if ( isset( $input['google_play_store_url'] ) ) {
			$sanitary_values['google_play_store_url'] = sanitize_text_field( $input['google_play_store_url'] );
		}

		if ( isset( $input['google_play_store_icon_url'] ) ) {
			$sanitary_values['google_play_store_icon_url'] = sanitize_text_field( $input['google_play_store_icon_url'] );
		}

		if ( isset( $input['google_play_store_tagline'] ) ) {
			$sanitary_values['google_play_store_tagline'] = sanitize_text_field( $input['google_play_store_tagline'] );
		}

		return $sanitary_values;
	}

	public function smartbanner_section_info() {
		
	}

	public function app_name_callback() {
		printf(
            '<input class="regular-text" type="text" name="wp_smartbanner_options_fields[app_name]" id="app_name" placeholder="%s" value="%s">',
            $this->get_default('app_name'),
			!empty( $this->smartbanner_options['app_name'] ) ? esc_attr( $this->smartbanner_options['app_name']) : ''
		);
	}

	public function author_name_callback() {
		printf(
            '<input class="regular-text" type="text" name="wp_smartbanner_options_fields[author_name]" id="author_name" placeholder="%s" value="%s">',
            $this->get_default('author_name'),
			!empty( $this->smartbanner_options['author_name'] ) ? esc_attr( $this->smartbanner_options['author_name']) : ''
		);
	}

	public function price_callback() {
		printf(
            '<input class="regular-text" type="text" name="wp_smartbanner_options_fields[price]" id="price" placeholder="%s" value="%s">',
            $this->get_default('price'),
			!empty( $this->smartbanner_options['price'] ) ? esc_attr( $this->smartbanner_options['price']) : ''
		);
	}

	public function view_label_callback() {
		printf(
            '<input class="regular-text" type="text" name="wp_smartbanner_options_fields[view_label]" id="view_label" placeholder="%s" value="%s">',
            $this->get_default('view_label'),
			!empty( $this->smartbanner_options['view_label'] ) ? esc_attr( $this->smartbanner_options['view_label']) : ''
		);
	}

	public function close_label_callback() {
		printf(
            '<input class="regular-text" type="text" name="wp_smartbanner_options_fields[close_label]" id="close_label" placeholder="%s" value="%s">',
            $this->get_default('close_label'),
			!empty( $this->smartbanner_options['close_label'] ) ? esc_attr( $this->smartbanner_options['close_label']) : ''
		);
	}

	public function show_on_ios_callback() {
		printf(
			'<input type="checkbox" name="wp_smartbanner_options_fields[show_on_ios]" id="show_on_ios" value="show_on_ios" %s> <label for="show_on_ios">Show the smartbanner on iOS devices?</label>',
			( !empty( $this->smartbanner_options['show_on_ios'] ) && $this->smartbanner_options['show_on_ios'] === 'show_on_ios' ) ? 'checked' : ''
		);
	}

	public function apple_app_store_url_callback() {
		printf(
            '<input class="large-text" type="url" name="wp_smartbanner_options_fields[apple_app_store_url]" id="apple_app_store_url" placeholder="%s" value="%s" required>',
            $this->get_default('apple_app_store_url'),
			!empty( $this->smartbanner_options['apple_app_store_url'] ) ? esc_attr( $this->smartbanner_options['apple_app_store_url']) : ''
		);
	}

	public function apple_app_store_icon_url_callback() {
		printf(
            '<input class="large-text" type="url" name="wp_smartbanner_options_fields[apple_app_store_icon_url]" id="apple_app_store_icon_url" placeholder="%s" value="%s" required>',
            $this->get_default('apple_app_store_icon_url'),
			!empty( $this->smartbanner_options['apple_app_store_icon_url'] ) ? esc_attr( $this->smartbanner_options['apple_app_store_icon_url']) : ''
		);
	}

	public function apple_app_store_tagline_callback() {
		printf(
            '<input class="regular-text" type="text" name="wp_smartbanner_options_fields[apple_app_store_tagline]" id="apple_app_store_tagline" placeholder="%s" value="%s">',
            $this->get_default('apple_app_store_tagline'),
			!empty( $this->smartbanner_options['apple_app_store_tagline'] ) ? esc_attr( $this->smartbanner_options['apple_app_store_tagline']) : ''
		);
	}

	public function show_on_android_callback() {
		printf(
			'<input type="checkbox" name="wp_smartbanner_options_fields[show_on_android]" id="show_on_android" value="show_on_android" %s> <label for="show_on_android">Show the smartbanner on Android devices?</label>',
			( !empty( $this->smartbanner_options['show_on_android'] ) && $this->smartbanner_options['show_on_android'] === 'show_on_android' ) ? 'checked' : ''
		);
	}

	public function google_play_store_url_callback() {
		printf(
            '<input class="large-text" type="url" name="wp_smartbanner_options_fields[google_play_store_url]" id="google_play_store_url" placeholder="%s" value="%s" required>',
            $this->get_default('google_play_store_url'),
			!empty( $this->smartbanner_options['google_play_store_url'] ) ? esc_attr( $this->smartbanner_options['google_play_store_url']) : ''
		);
	}

	public function google_play_store_icon_url_callback() {
		printf(
            '<input class="large-text" type="url" name="wp_smartbanner_options_fields[google_play_store_icon_url]" id="google_play_store_icon_url" placeholder="%s" value="%s" required>',
            $this->get_default('google_play_store_icon_url'),
			!empty( $this->smartbanner_options['google_play_store_icon_url'] ) ? esc_attr( $this->smartbanner_options['google_play_store_icon_url']) : ''
		);
	}

	public function google_play_store_tagline_callback() {
		printf(
            '<input class="regular-text" type="text" name="wp_smartbanner_options_fields[google_play_store_tagline]" id="google_play_store_tagline" placeholder="%s" value="%s">',
            $this->get_default('google_play_store_tagline'),
			!empty( $this->smartbanner_options['google_play_store_tagline'] ) ? esc_attr( $this->smartbanner_options['google_play_store_tagline']) : ''
		);
    }
    
    public function get_default( $key ){
        if( !empty( parent::$defaults[ $key ] ) ){
            return parent::$defaults[ $key ];
        }
        return '';
    }

}

/* 
 * Retrieve this value with:
 * $smartbanner_options = get_option( 'wp_smartbanner_options_fields' ); // Array of All Options
 * $app_name = $smartbanner_options['app_name']; // App name
 * $author_name = $smartbanner_options['author_name']; // Author name
 * $price = $smartbanner_options['price']; // Price
 * $view_label = $smartbanner_options['view_label']; // View label
 * $close_label = $smartbanner_options['close_label']; // Close label
 * $show_on_ios = $smartbanner_options['show_on_ios']; // Show on iOs
 * $apple_app_store_url = $smartbanner_options['apple_app_store_url']; // Apple App Store url
 * $apple_app_store_icon_url = $smartbanner_options['apple_app_store_icon_url']; // Apple App Store Icon url
 * $apple_app_store_tagline = $smartbanner_options['apple_app_store_tagline']; // Apple App Store tagline
 * $show_on_android = $smartbanner_options['show_on_android']; // Show on Android
 * $google_play_store_url = $smartbanner_options['google_play_store_url']; // Google Play Store url
 * $google_play_store_icon_url = $smartbanner_options['google_play_store_icon_url']; // Google Play Store Icon url
 * $google_play_store_tagline = $smartbanner_options['google_play_store_tagline']; // Google Play Store tagline
 */
